apiVersion: batch/v1
kind: Job

metadata:
  name: automation-tests

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: automation-tests
          image: ghcr.io/mdzakir67/hybrid_automation_framework:local
          imagePullPolicy: IfNotPresent

          command: ["/bin/bash", "-c"]

          args:
            - |
              set +e
              /usr/local/bin/entrypoint.sh
              TEST_EXIT=$?

              echo "Test exit code: $TEST_EXIT"
              echo "Keeping container alive for debugging..."
              sleep 300

              exit $TEST_EXIT

          env:
            - name: BROWSER
              value: "chrome"

            - name: HEADLESS
              value: "true"

            - name: ALLURE_RESULTS_DIR
              value: "/results"

          volumeMounts:
            - name: allure-results
              mountPath: /results

      volumes:
        - name: allure-results
          persistentVolumeClaim:
            claimName: allure-results-pvc