name: Automation Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run Automation Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Set up Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Run automation tests
        run: mvn clean test -Denv=qa

      - name: Create Allure HTML report
        if: always()
        run: mvn allure:report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Allure HTML report
          path: target/site/allure-maven-plugin/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: scenario-logs
          path: target/logs/
          if-no-files-found: warn

      - name: Upload Cucumber report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: cucumber-report
          path: target/cucumber-report.html
          if-no-files-found: warn

      - name: Configure GitHub Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload Allure report to Pages
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
         path: target/site/allure-maven-plugin/

  deploy:
    name: Deploy Allure Report
    needs: test
    if: always()
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
